name: Deploy to Hostinger VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            export PATH=$PATH:/usr/local/go/bin
            cd /opt/hello-world-api
            git pull origin main
            CGO_ENABLED=0 GOOS=linux go build \
              -ldflags="-w -s" \
              -o bin/server \
              ./cmd/api
            sudo systemctl restart hello-world-api
            sudo systemctl status hello-world-api --no-pager
            echo "✅ Deploy sukses! https://api.rifanid.com"
